on: push
name: benchmark

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: build-env
        run: |
          echo "CORES=$(nproc)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: benchmark with snakemake
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .test
          snakefile: "workflow/Snakefile"
          args: "--jobs $CORES --use-conda"
          show-disk-usage-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: benchmarks
          path: |
            .test/**
            output/**
